SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `wan` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `wan`;

CREATE TABLE IF NOT EXISTS `knoten` (
`Knoten_Name` varchar(40) DEFAULT NULL,
`Knoten_PLZ` int(5) NOT NULL,
`Knoten_Ort` varchar(40) NOT NULL,
`Knoten_Strasse` varchar(40) NOT NULL,
`Knoten_Hnr` int(3) NOT NULL,
`Knoten_Breitengrad` varchar(50) NOT NULL,
`Knoten_Laengengrad` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `leitung` (
`Leitung_Name` varchar(40) DEFAULT NULL,
`Leitung_Start` varchar(40) NOT NULL,
`Leitung_Ende` varchar(40) NOT NULL,
`Kommentar` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
